### ISSUE TITLE
Gamise platform-Gamification/add points and achievement

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#1]
**pre-condition:** admin user
**scenario:** when adding points and achievement points and title and description , users have no limit of how much text can type in, admin user also has not limit of how much digits can add to the points, admin tries to create new badge and rewards in the Gamification.
**post condition:**
adding multiple lines of text do not wrap and cause the text to appear on very long line on the screen.
adding points more 9 digits cause the system crashing (Internal server error).
creating new badge and rewards without adding an image will cause (Internal server error) .

**Comment by RachelXur** [comment]
Update:
Pictures of badges and rewards are required.
The name and description of each gamification element should be brief, and it is better to summary in one sentence. So, I didn't change it.

**Comment by maysamsameer** [comment]
pre-condition: admin
scenario: adding badges , achievement, points.
post condition: rules have been added to the text boxes when adding new points , badges and acheivements ,  and it is working properly and there is no system crashing. The forementioned issue has been solved
