### ISSUE TITLE
Gamise Platform-User Update password 

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#2]
**pre-condition**: normal users
**scenario:** user clicks on (Hello,username -> change password) and wants to update the current password .
**post-condition:**
- when user type current and the new password, it is visible by default and there is no possible option to make it invisible.
- system does not object that the new chosen password is same as the old password - no password specification.

**Comment by RachelXur** [comment]
Update:
Changed it to invisible.

**Comment by maysamsameer** [comment]
post condition: the formentioned issue has been solved and user password is no invisible
