### ISSUE TITLE
Gamise Platform- User Registration date not correct

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#3]
**pre-condition:** normal users
**scenario:** user registered and check the registration date through points -> points records
**post-condition:** registeration of user as normal user was on 2021-05-31 but in the website shows 2021-06-01

**Comment by RachelXur** [comment]
This is because the time zone of the platform is the UTC time zone. It is 5 hours later than the time zone here. I have mentioned it in Instruction.

**Comment by RachelXur** [comment]
The reason why I use the UTC time zone is that for all the users all over the world, the UTC time zone will be the same and

**Comment by maysamsameer** [comment]
I think it would be great to notify the user , or add the time of the registration, it may create some confusion for first time users when they register or have shared an activity with time gap between their time and the system time/date.

**Comment by RachelXur** [comment]
When I ask for the participates in evaluating the platform. They need to read the Instruction carefully to understand the rules of the platform. But I will also add the time zone notification on Terms and conditions to notice them when they register the platform. The UTC time zone is 4 hours later than the time zone here. Sorry for the mistake.

**Comment by RachelXur** [comment]
Update:
Solved. Every time when users submit an experience or report. It will flash the date and time of submission.

**Comment by maysamsameer** [comment]
pre condition: users
scenario: user registration and user shares experience.
post condition: system shows the registeration and sharing experience time and date according to UTC time with a notification at the top of the current user's page.
