### ISSUE TITLE
 User Sharing experience - suggestion 

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#4]
**pre-condition:** normal users and IT users
**Scenario:** when users intend to share experience on their main page, if the user write on the text box where it says "want to share something" and click share then it takes the user to fill in another empty form and what the user wrote before the new form popped up , it will not be transferred to it .
**post condition**: for better functioning of the website and not to do the task of sharing the experience twice , a hidden text box can appear  when user click on the first text box where it says "want to share something" , instead of writing on the first text box and write the same information again in the new form , or any other mechanism.

**Comment by RachelXur** [comment]
Solved. Changed it to a button. Users cannot write experience on the homepage.

**Comment by maysamsameer** [comment]
pre-condition: normal users and IT users
Scenario: user intend to write and share experience
post condition: user clicking on share experience textbox will launch a page which filling the title and description of the experience. The forementioned issue has been solved
