### ISSUE TITLE
User request to withdraw issue / same as NG

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#5]
**pre-condition**: normal users
**Scenario**: user receives email with daily news or tips, when user scroll down , if wish to withdraw by click on the link in the email content (withdraw).
**Post condition:**
- if another user is still logged in the same device then a  conflict between two account will occur (every user should have their copy and user who clicked withdraw link show be directed to the log in page)
- suggestion: admin could be notified if a user withdrew from the system

**Comment by RachelXur** [comment]
Solved. Normal users can request a withdrawal from the daily email. However, the IT department can only withdrawal from the Admin side. The withdrawal record will be stored in the database.

**Comment by maysamsameer** [comment]
post condition: if a certain user is logged in and another user wants to withdraw , then he or she would have their own copy of the platform and no conflict will occur. the forementioned issue has been solved.
