### ISSUE TITLE
Authentication of users on the registration process

### ISSUE THREAD

**Issue by maysamsameer** [RachelXur/GamiSE_GM#7]
**pre-condition:** all users.
**Scenario:** when register a new user is being registered , if the user entered a wrong email address, then a different user will be registered and can receive gamise related information specially if the user did not login after registration.

**post condition:** a mechanism for new user authentication could be provide , for instance, sending a randomly generated code to to the user email which user can click to confirm his or her identity and safely share and use gamise.

**Comment by RachelXur** [comment]
Solved. New users who register on the platform will receive an email to confirm their registration. After they confirm the email, they can log in to the platform.

**Comment by maysamsameer** [comment]
post condition: recent registered user will receive an email for verification identity and cant log in until they click the email . the issue has been solved.
